services:
  
  backend:
    container_name: dev_backend
    hostname: dev_backend
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: dev
    ports:
      - 8000:8000
      - 5678:5678
    env_file:
      - .env
    restart: no
    command: bash /backend/scripts/run-dev.sh
    develop:
      watch:
        - action: sync
          path: ./backend/app
          target: /backend/app

        - action: rebuild
          path: ./backend/pyproject.toml
          target: /backend/pyproject.toml
    networks: 
      - dev_network


networks:
  dev_network: