x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "20m"
    max-file: "3"

services:

  db:
    container_name: postgresql
    hostname: postgresql
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 4
    networks: 
      - default
    logging: *default-logging 

  backend:
    container_name: fastapi
    hostname: fastapi
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: prod
    env_file:
      - .env
      - backend/.env
    restart: always
    command: bash /backend/scripts/run.sh
    depends_on:
      cache:
        condition: service_healthy
      broker:
        condition: service_healthy
      db:
        condition: service_healthy
    networks: 
      - default
    logging: *default-logging

  workers:
    container_name: celery
    hostname: celery
    build:
      context: .
      dockerfile: workers/Dockerfile
      target: prod
    env_file:
      - .env
      - workers/.env
    restart: always
    command: bash /workers/scripts/run.sh
    depends_on:
      cache:
        condition: service_healthy
      broker:
        condition: service_healthy
    networks: 
      - default
    logging: *default-logging
    
  frontend:
    container_name: frontend
    hostname: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    restart: always
    ports:
      - 80:80
    networks:
      - default
    logging: *default-logging

  cache:
    container_name: redis
    hostname: redis
    image: redis:7.4.0-alpine
    env_file:
      - .env
    volumes:
      - cache_data:/data
    restart: always
    entrypoint: ["redis-server"]
    command: ["--requirepass", "$REDIS_PASSWORD"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - default
    logging: *default-logging
  
  broker:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3-management-alpine
    env_file:
      - .env
    volumes:
      - broker_data:/var/lib/rabbitmq
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 5s
      timeout: 10s
      retries: 4
    networks:
      - default
    logging: *default-logging

  loki:
    profiles: ["monitoring"]
    container_name: loki
    image: grafana/loki:3.7.2
    expose:
      # This is the main port through which Loki receives logs (from Alloy) and sends logs (to Grafana)
      - 3100
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./monitoring/loki-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki
    restart: always
    healthcheck:
      test: [ "CMD", "/usr/bin/loki", "-health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  alloy:
    profiles: ["monitoring"]
    container_name: alloy
    image: grafana/alloy:v1.16.1
    user: root
    volumes:
      - ./monitoring/alloy-config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: run --server.http.listen-addr=0.0.0.0:12345 /etc/alloy/config.alloy
    depends_on:
      loki:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:12345/-/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

volumes:
  db_data:
  cache_data:
  broker_data:
  loki_data:

networks:
  default: