services:

  postgresql:
    container_name: dev_postgresql
    hostname: dev_postgresql
    image: postgres:15-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - dev_db_data:/var/lib/postgresql/data
    restart: no
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 4
    networks: 
      - dev_network
  
  backend:
    container_name: dev_backend
    hostname: dev_backend
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: dev
    ports:
      - 8000:8000
      - 5678:5678
    env_file:
      - .env
    restart: no
    command: bash /backend/scripts/run-dev.sh
    depends_on:
      redis:
        condition: service_started
      rabbit:
        condition: service_healthy
      postgresql:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./backend/app
          target: /backend/app

        - action: rebuild
          path: ./backend/pyproject.toml
          target: /backend/pyproject.toml
    networks: 
      - dev_network


  redis:
    container_name: dev_redis
    hostname: dev_redis
    image: redis:7.4.0-alpine
    ports:
      - 6379:6379
    env_file:
      - .env
    volumes:
      - dev_cache_data:/data
    restart: no
    entrypoint: ["redis-server"]
    command: ["--requirepass", "$REDIS_PASSWORD"]
    networks:
      - dev_network

  
  rabbit:
    container_name: dev_broker
    hostname: dev_broker
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - .env
    volumes:
      - dev_broker_data:/var/lib/rabbitmq
    restart: no
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 5s
      timeout: 10s
      retries: 4
    networks:
      - dev_network

volumes:
  dev_db_data:
  dev_cache_data:
  dev_broker_data:

networks:
  dev_network: