"""empty message

Revision ID: 2283c4287d7d
Revises: c758b95b8856
Create Date: 2025-06-25 13:55:25.818899

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2283c4287d7d'
down_revision: Union[str, None] = 'c758b95b8856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'major_language')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('major_language', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
