"""empty message

Revision ID: 5eb8a38a6d93
Revises:
Create Date: 2025-01-29 19:18:29.171971

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlmodel.sql import sqltypes as sm

# revision identifiers, used by Alembic.
revision: str = '5eb8a38a6d93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('name', sm.AutoString(length=20), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('hashed_password', sm.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
