"""empty message

Revision ID: 85f057a9da4d
Revises: 5eb8a38a6d93
Create Date: 2025-02-23 14:29:03.659940

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b505969ebe30'
down_revision: Union[str, None] = '5eb8a38a6d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summary',
                    sa.Column('video_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
                    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('size', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.CheckConstraint("size IN ('small', 'medium', 'large')", name='valid_size_check'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_summary',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Uuid(), nullable=False),
                    sa.Column('summary_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['summary_id'], ['summary.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_summary')
    op.drop_table('summary')
    # ### end Alembic commands ###
