"""empty message

Revision ID: c758b95b8856
Revises: ff4be524b221
Create Date: 2025-04-10 13:41:33.908542

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c758b95b8856'
down_revision: Union[str, None] = 'ff4be524b221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('summary', 'text',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('summary', 'text',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###
