"""empty message

Revision ID: ff4be524b221
Revises: b505969ebe30
Create Date: 2025-02-10 22:58:58.912668

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ff4be524b221'
down_revision: Union[str, None] = 'b505969ebe30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
                    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('major_language', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
                    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('link')
                    )
    op.create_foreign_key('fk_summary_video', 'summary', 'video', ['video_link'], ['link'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_summary_video', 'summary', type_='foreignkey')
    op.drop_table('video')
    # ### end Alembic commands ###
